### ISSUE TITLE
Refine theme

### ISSUE THREAD

**Issue by kmillet** [OnroerendErfgoed/oe-sphinx-theme#1]
The theme is already quite similar to https://github.com/OnroerendErfgoed/sphinx-oe-theme. However still some small refinements in css are needed.

**Comment by koenedaele** [comment]
No idea what this is about. @kmillet Is this still an issue?

**Comment by kmillet** [comment]
This is an old issue. As I remember one of the things was the background of the header image that was showing left of the title on bigger screens. But I guess this can be closed now...
