### ISSUE TITLE
Why do we have 2 sphinx themes?

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/oe-sphinx-theme#4]

**Comment by kmillet** [comment]
the first one was made in bootstrap, later I switched it to foundation to make it more fitting with the default foundation theme. We could remove the bootstrap theme...

**Comment by koenedaele** [comment]
Ok, either remove the other one. Or edit the README to say that the theme is not being maintained at that people should use this one.

**Comment by kmillet** [comment]
ok, readme updated
