### ISSUE TITLE
Why is the theme not present on pypi?

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/oe-sphinx-theme#5]

**Comment by kmillet** [comment]
Mostly because I knew there were still some issues. However as it is already tagged and released I think it should indeed be there, I will add it..

**Comment by koenedaele** [comment]
Will be fixed when we release 0.2.0

**Comment by koenedaele** [comment]
Tested the latest master version with ablog and everything works great now. I think we can release 0.2.0 if #1 is ok.

**Comment by kmillet** [comment]
Now online on https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=oe-sphinx-theme

**Comment by koenedaele** [comment]
Thx. If you can, please make me and Wouter maintainers or owners so that you're not the only one responsible.

**Comment by kmillet** [comment]
Ok, done.
