### ISSUE TITLE
Not a lot of room for the title

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/oe-sphinx-theme#7]
The title of a document doesn't get a lot of space. Frequently the title ends up running into the body. Not sure how to fix this. Smaller font for the title? Move the Lion more to the right to create more room? Change the design: Put the Lion at the outer left and move the title into the purple bar under the Logo and Picture band? Any other ideas?

**Comment by taeymma** [comment]
Your suggestions differ a lot from the current style. I'll talk to @TOM-VC about this.

Do you have a screenshot of the problem?

**Comment by koenedaele** [comment]
![image](https://cloud.githubusercontent.com/assets/676018/18634794/da1cf5fc-7e82-11e6-93ce-b00b95142edb.png)

**Comment by koenedaele** [comment]
![image](https://cloud.githubusercontent.com/assets/676018/18634872/31885534-7e83-11e6-8c00-b7e7b06134a6.png)

**Comment by koenedaele** [comment]
Pragmatic solution. Remove the title from the header. Just use the logo and "Vlaanderen is Erfgoed". Add the title above the TOC box.
